Repository SeonHyungJo/YourHome, pull requests merged in 2018-10, with the labels that each got.

#2 1 Week - Regular Pull Request
  front/package-lock.json
  front/package.json
  front/public/home.ico
  front/public/index.html
  front/src/App.jsx
  front/src/App.scss
  front/src/component/header/HeaderContainer.jsx
  front/src/component/nav/NavContainer.jsx
  front/src/component/pageTemplate/PageTemplate.jsx
  front/src/index.js
  front/src/lib/api/auth.js
  front/src/pages/admin/AdminMain.jsx
  front/src/pages/common/auth/Login.jsx
  front/src/pages/common/auth/index.js
  front/src/pages/user/UserMain.jsx
  front/src/redux/configureStore.js
  front/src/redux/modules/auth.js
  front/src/redux/modules/index.js
  front/src/store/index.js
Labels: Merge

#4 :house: seonhyungjo / test / Pull request TEST
  front/src/component/pageTemplate/PageTemplate.jsx
Labels: TEST

#3 :house: BKJang / feat / User, Admin 컴포넌트 index.js 추가
  front/src/App.jsx
  front/src/pages/admin/index.js
  front/src/pages/user/index.js
Labels: Merge

#11 Server seonhyungjo
  server/.gitignore
  server/app.js
  server/models/books.js
  server/models/sample_schema.js
  server/models/users.js
  server/package.json
  server/router/api/admin.js
  server/router/api/user.js
  server/router/auth/auth.controller.js
  server/router/auth/index.js
  server/yarn.lock
Labels: enhancement

#12 Add Server Feature
  server/.gitignore
  server/app.js
  server/models/books.js
  server/models/sample_schema.js
  server/models/users.js
  server/package.json
  server/router/api/admin.js
  server/router/api/user.js
  server/router/auth/auth.controller.js
  server/router/auth/index.js
  server/yarn.lock
Labels: Merge
